### ISSUE TITLE
bug: how to verify that OTP

### ISSUE THREAD

**Issue by mohssineAboutaj** [sadiqsalau/laravel-otp-password#1]
I want to use this package with APi
Is there a way to verify that OTP with `$request->validate()` ?

**Comment by sadiqsalau** [comment]
Yes, this package is designed with API in mind, you can use the package for an API...

```php

$request->validate([ 'email' => ['required', 'email'] ]);

$status = OtpPassword::sendOTP(
    $request->only('email')
);

return response()->json([
   'status' => $status === OtpPassword::OTP_SENT,
   'message' => __($status)
]);

```

**Comment by sadiqsalau** [comment]
Once the password reset OTP has been sent, you need to setup the route to verify the OTP using the parent package [laravel-otp](https://github.com/sadiqsalau/laravel-otp)..

**Comment by mohssineAboutaj** [comment]
yup, I found an article explain this in example
https://medium.com/@sadiqsalau/sending-and-verifying-otp-codes-in-laravel-the-easy-way-b946946bf467
Thank you so much
